#!/bin/sh
updatedb --localpaths='/home/bau15043 /' \
	--prunepaths='
		.*Logs
		.*/LogFiles
		.*Temp
		.*Tmp
        /cygdrive/c
        /cygdrive/e/10_apps
        /cygdrive/e/System*
        /cygdrive/e/$RECYCLE.BIN
        /cygdrive/p
        /cygdrive/h
        /cygdrive/v
        /cygdrive/w
        /cygdrive/y
		/cygdrive/c/$Recycle.*
		/cygdrive/c/PerfLogs
		/cygdrive/c/ProgramData
		/cygdrive/c/Recovery
		/cygdrive/c/System.*
		/cygdrive/c/Progra*
		/cygdrive/c/Program.*/WindowsApps
		/cygdrive/c/Program.*/.*/cygdrive/crashReports
		/cygdrive/c/Users/Administrator
		/cygdrive/c/Users/cygdrive/cyg_server
		/cygdrive/c/Users/Public
		/cygdrive/c/Windows/AppCompat/Programs
		/cygdrive/c/Windows/AUInstallAgent
		/cygdrive/c/Windows/cygdrive/cSC
		/cygdrive/c/Windows/LiveKernelReports
		/cygdrive/c/Windows/Minidump
		/cygdrive/c/Windows/PLA
		/cygdrive/c/Windows/Prefetch
		/cygdrive/c/Windows/Resources/Themes
		/cygdrive/c/Windows/ServiceProfiles
		/cygdrive/c/Windows/security
		/cygdrive/c/Windows/ServiceProfiles
		/cygdrive/c/Windows/Sys.*/cygdrive/com/dmp
		/cygdrive/c/Windows/Sys.*/cygdrive/config
		/cygdrive/c/Windows/Sys.*/MsDtc
		/cygdrive/c/Windows/Sys.*/networklist
		/cygdrive/c/Windows/Sys.*/sru
		/cygdrive/c/Windows/Sys.*/Tasks
		/cygdrive/c/Windows/WinSxS
		/cygdrive/c/Windows.old
		/cygdrive/c/Windows/*
		/cygdrive/c/System*        
		/cygdrive/c/Users/aau01133
		/cygdrive/c/Users/aau07040
		/cygdrive/c/Users/aau02063
		/cygdrive/c/Users/aau14854
		/cygdrive/c/Users/aau15043
		/cygdrive/c/Users/bau01133
		/cygdrive/c/Users/bau07040
		/cygdrive/c/MSOCache/*
		/cygdrive/c/Program*
		/cygdrive/c/Program*/*
        /proc
		/tmp
		/usr/tmp
		/var/tmp'
